import { z } from 'zod';

// =============================================================================
// Student DTOs — Zod schemas for student endpoints
// =============================================================================

export const CreateStudentDto = z.object({
  branchId: z.string().optional().nullable(),
  classId: z.string().optional().nullable(),
  sectionId: z.string().optional().nullable(),
  academicYearId: z.string().optional().nullable(),
  studentId: z.string().min(1, 'Student ID is required'),
  firstName: z.string().min(1, 'First name is required').max(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  dateOfBirth: z.coerce.date().optional().nullable(),
  gender: z.preprocess((val) => typeof val === 'string' ? val.toUpperCase() : val, z.enum(['MALE', 'FEMALE', 'OTHER'])).optional().nullable(),
  phone: z.string().max(20).optional().nullable(),
  email: z.string().email().optional().nullable(),
  address: z.string().max(500).optional().nullable(),
  bloodGroup: z.string().max(5).optional().nullable(),
  religion: z.string().max(50).optional().nullable(),
  nationality: z.string().max(100).default('Bangladeshi'),
  admissionDate: z.coerce.date().optional(),
  rollNumber: z.string().max(50).optional().nullable(),
  avatarUrl: z.string().optional().nullable(),
});

export const UpdateStudentDto = CreateStudentDto.partial().extend({
  status: z.enum(['ACTIVE', 'INACTIVE', 'GRADUATED', 'TRANSFERRED']).optional(),
});

export const StudentQueryDto = z.object({
  page: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().positive().max(100).default(20),
  search: z.string().optional(),
  classId: z.string().cuid().optional(),
  sectionId: z.string().cuid().optional(),
  branchId: z.string().cuid().optional(),
  academicYearId: z.string().cuid().optional(),
  status: z.enum(['ACTIVE', 'INACTIVE', 'GRADUATED', 'TRANSFERRED']).optional(),
});

export const StudentIdParamDto = z.object({
  id: z.string().cuid('Invalid student ID'),
});

export const CreateStudentDocumentDto = z.object({
  name: z.string().min(1, 'Document name is required'),
  type: z.string().min(1, 'Document type is required'),
  fileUrl: z.string().url('Invalid file URL'),
  fileSize: z.number().int().positive().optional(),
  mimeType: z.string().optional(),
});

// Bulk import — one row from an uploaded Excel/CSV sheet. Deliberately more
// forgiving than CreateStudentDto (className/sectionName are human-readable
// strings resolved server-side, not internal cuids) since this is filled in
// by hand by school staff, not generated by the app's own UI.
export const BulkImportRowDto = z.object({
  studentId: z.string().min(1, 'Student ID is required'),
  firstName: z.string().min(1, 'First name is required').max(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  className: z.string().min(1).optional().nullable(),
  sectionName: z.string().min(1).optional().nullable(),
  rollNumber: z.string().max(50).optional().nullable(),
  gender: z.preprocess(
    (val) => (typeof val === 'string' ? val.toUpperCase() : val),
    z.enum(['MALE', 'FEMALE', 'OTHER']).optional().nullable(),
  ),
  dateOfBirth: z.coerce.date().optional().nullable(),
  phone: z.string().max(20).optional().nullable(),
  email: z.string().email().optional().nullable().or(z.literal('')),
  bloodGroup: z.string().max(5).optional().nullable(),
});

export type BulkImportRowDtoType = z.infer<typeof BulkImportRowDto>;

export type CreateStudentDtoType = z.infer<typeof CreateStudentDto>;
export type UpdateStudentDtoType = z.infer<typeof UpdateStudentDto>;
export type StudentQueryDtoType = z.infer<typeof StudentQueryDto>;
export type CreateStudentDocumentDtoType = z.infer<typeof CreateStudentDocumentDto>;
