import { z } from 'zod';

// =============================================================================
// Student DTOs — Zod schemas for student endpoints
// =============================================================================

export const CreateStudentDto = z.object({
  branchId: z.string().optional().nullable(),
  classId: z.string().optional().nullable(),
  sectionId: z.string().optional().nullable(),
  academicYearId: z.string().optional().nullable(),
  studentId: z.string().min(1, 'Student ID is required'),
  firstName: z.string().min(1, 'First name is required').max(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  dateOfBirth: z.coerce.date().optional().nullable(),
  gender: z.preprocess((val) => typeof val === 'string' ? val.toUpperCase() : val, z.enum(['MALE', 'FEMALE', 'OTHER'])).optional().nullable(),
  phone: z.string().max(20).optional().nullable(),
  // Required (not just optional) — every student created here also gets a
  // linked login User account (role STUDENT), so the Students page and the
  // Users page never diverge. Email is the User's unique login identifier.
  email: z.string().email('A valid email is required to create the student login'),
  password: z.string().min(8, 'Password must be at least 8 characters'),
  address: z.string().max(500).optional().nullable(),
  permanentAddress: z.string().max(500).optional().nullable(),
  bloodGroup: z.string().max(5).optional().nullable(),
  religion: z.string().max(50).optional().nullable(),
  nationality: z.string().max(100).default('Bangladeshi'),
  admissionDate: z.coerce.date().optional(),
  rollNumber: z.string().max(50).optional().nullable(),
  department: z.string().max(50).optional().nullable(),
  categoryId: z.string().min(1).optional().nullable(),
  caste: z.string().max(100).optional().nullable(),
  // Deliberately free-text, not numeric — matches the source reference's
  // ungoverned height/weight fields.
  height: z.string().max(20).optional().nullable(),
  weight: z.string().max(20).optional().nullable(),
  // Comma-separated free text, e.g. "Reading,Singing" — matches the source
  // reference's simple checkbox-list hobby field, no separate join table.
  hobbies: z.string().max(200).optional().nullable(),
  avatarUrl: z.string().optional().nullable(),
});

export const UpdateStudentDto = CreateStudentDto.partial().extend({
  status: z.enum(['ACTIVE', 'INACTIVE', 'GRADUATED', 'TRANSFERRED', 'PENDING']).optional(),
});

export const StudentQueryDto = z.object({
  page: z.coerce.number().int().positive().default(1),
  pageSize: z.coerce.number().int().positive().max(1000).default(20),
  search: z.string().optional(),
  classId: z.string().min(1).optional(),
  sectionId: z.string().min(1).optional(),
  branchId: z.string().min(1).optional(),
  academicYearId: z.string().min(1).optional(),
  status: z.enum(['ACTIVE', 'INACTIVE', 'GRADUATED', 'TRANSFERRED', 'PENDING']).optional(),
});

export const StudentIdParamDto = z.object({
  id: z.string().min(1, 'Invalid student ID'),
});

export const CreateStudentDocumentDto = z.object({
  name: z.string().min(1, 'Document name is required'),
  type: z.string().min(1, 'Document type is required'),
  fileUrl: z.string().url('Invalid file URL'),
  fileSize: z.number().int().positive().optional(),
  mimeType: z.string().optional(),
});

// Bulk import — one row from an uploaded Excel/CSV sheet. Deliberately more
// forgiving than CreateStudentDto (className/sectionName are human-readable
// strings resolved server-side, not internal cuids) since this is filled in
// by hand by school staff, not generated by the app's own UI.
export const BulkImportRowDto = z.object({
  studentId: z.string().min(1, 'Student ID is required'),
  firstName: z.string().min(1, 'First name is required').max(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  className: z.string().min(1).optional().nullable(),
  sectionName: z.string().min(1).optional().nullable(),
  rollNumber: z.string().max(50).optional().nullable(),
  gender: z.preprocess(
    (val) => (typeof val === 'string' ? val.toUpperCase() : val),
    z.enum(['MALE', 'FEMALE', 'OTHER']).optional().nullable(),
  ),
  dateOfBirth: z.coerce.date().optional().nullable(),
  phone: z.string().max(20).optional().nullable(),
  email: z.string().email().optional().nullable().or(z.literal('')),
  bloodGroup: z.string().max(5).optional().nullable(),
});

export type BulkImportRowDtoType = z.infer<typeof BulkImportRowDto>;

// PATCH /students/roll-numbers — Assign Roll Numbers screen. sectionId +
// every assignment's studentId are re-validated server-side against the
// caller's institution/section in one findMany before any write happens.
export const RollNumberAssignmentDto = z.object({
  studentId: z.string().min(1, 'studentId is required'),
  rollNumber: z.string().min(1, 'rollNumber is required').max(50),
});

export const UpdateRollNumbersDto = z.object({
  sectionId: z.string().min(1, 'sectionId is required'),
  assignments: z.array(RollNumberAssignmentDto).min(1, 'At least one assignment is required'),
});

// POST /students/:id/reset-password — password is optional; when omitted the
// service generates one server-side and returns it once, plaintext, in the
// response (never logged/stored in plaintext).
export const ResetStudentPasswordDto = z.object({
  password: z.string().min(8, 'Password must be at least 8 characters').optional(),
});

// POST /students/bulk-assign-class — Bulk Assign Class screen.
export const BulkAssignClassDto = z.object({
  studentIds: z.array(z.string().min(1)).min(1, 'At least one studentId is required'),
  classId: z.string().min(1, 'classId is required'),
  sectionId: z.string().min(1).optional(),
});

// POST /student-applications/apply — public, unauthenticated Online
// Registration form. institutionSlug resolves the tenant server-side (never
// trust a client-supplied institutionId on a public endpoint). Deliberately
// narrower than CreateStudentDto — no email/password (no login is
// provisioned until an admin approves the application).
export const PublicStudentApplicationDto = z.object({
  institutionSlug: z.string().min(1, 'institutionSlug is required'),
  firstName: z.string().min(1, 'First name is required').max(100),
  lastName: z.string().min(1, 'Last name is required').max(100),
  dateOfBirth: z.coerce.date().optional().nullable(),
  gender: z.preprocess((val) => typeof val === 'string' ? val.toUpperCase() : val, z.enum(['MALE', 'FEMALE', 'OTHER'])).optional().nullable(),
  classId: z.string().min(1).optional().nullable(),
  guardianFirstName: z.string().min(1, 'Guardian first name is required').max(100),
  guardianLastName: z.string().min(1, 'Guardian last name is required').max(100),
  guardianEmail: z.string().email('A valid guardian email is required'),
  guardianPhone: z.string().min(1, 'Guardian mobile is required').max(20),
});

// POST /students/:id/approve — Online Registrations review screen. Approving
// provisions the student's login (none exists yet for a pending application),
// so an email is required; a password is generated server-side and returned
// once, same pattern as ResetStudentPasswordDto.
export const ApproveStudentApplicationDto = z.object({
  email: z.string().email('A valid email is required to create the student login'),
});

export type CreateStudentDtoType = z.infer<typeof CreateStudentDto>;
export type UpdateStudentDtoType = z.infer<typeof UpdateStudentDto>;
export type StudentQueryDtoType = z.infer<typeof StudentQueryDto>;
export type CreateStudentDocumentDtoType = z.infer<typeof CreateStudentDocumentDto>;
export type UpdateRollNumbersDtoType = z.infer<typeof UpdateRollNumbersDto>;
export type PublicStudentApplicationDtoType = z.infer<typeof PublicStudentApplicationDto>;
export type ApproveStudentApplicationDtoType = z.infer<typeof ApproveStudentApplicationDto>;
export type ResetStudentPasswordDtoType = z.infer<typeof ResetStudentPasswordDto>;
export type BulkAssignClassDtoType = z.infer<typeof BulkAssignClassDto>;
