/**
 * UI strings used by the public site chrome and the blocks. The site's
 * language follows the site's own toggle (not the dashboard's), so these
 * live here rather than in the dashboard dictionary.
 */
import type { SiteLang } from './types';

const BN: Record<string, string> = {
  'Home': 'হোম',
  'Menu': 'মেনু',
  'Close menu': 'মেনু বন্ধ করুন',
  'Open menu': 'মেনু খুলুন',
  'Language': 'ভাষা',
  'Skip to content': 'মূল বিষয়বস্তুতে যান',
  'Preview — not published': 'প্রিভিউ — এখনো প্রকাশিত হয়নি',
  'You are viewing a draft. Visitors can’t see these changes yet.': 'আপনি খসড়া দেখছেন। দর্শকরা এখনো এই পরিবর্তন দেখতে পাবেন না।',
  'Page not found': 'পৃষ্ঠাটি পাওয়া যায়নি',
  'The page you’re looking for doesn’t exist or hasn’t been published yet.': 'আপনি যে পৃষ্ঠাটি খুঁজছেন তা নেই অথবা এখনো প্রকাশিত হয়নি।',
  'Go to the home page': 'হোম পেজে যান',
  'This website isn’t available': 'এই ওয়েবসাইটটি পাওয়া যাচ্ছে না',
  'It may not be published yet, or the address is wrong.': 'এটি হয়তো এখনো প্রকাশিত হয়নি, অথবা ঠিকানাটি ভুল।',
  'Something went wrong': 'কিছু একটা সমস্যা হয়েছে',
  'Try again': 'আবার চেষ্টা করুন',
  'Loading…': 'লোড হচ্ছে…',
  'News & updates': 'খবর ও আপডেট',
  'Read more': 'আরও পড়ুন',
  'Back to news': 'খবরে ফিরে যান',
  'No posts yet': 'এখনো কোনো পোস্ট নেই',
  'News and updates will appear here once they’re published.': 'প্রকাশিত হলে খবর ও আপডেট এখানে দেখা যাবে।',
  'Previous': 'আগের',
  'Next': 'পরের',
  'Page {page} of {pages}': 'পৃষ্ঠা {page} / {pages}',
  'All rights reserved.': 'সর্বস্বত্ব সংরক্ষিত।',
  'Quick links': 'দ্রুত লিংক',
  'Contact': 'যোগাযোগ',
  'Follow us': 'আমাদের অনুসরণ করুন',
  'Phone': 'ফোন',
  'Email': 'ইমেইল',
  'Address': 'ঠিকানা',
  'Notices': 'নোটিশ',
  'No notices right now': 'এই মুহূর্তে কোনো নোটিশ নেই',
  'Published notices for everyone will appear here.': 'সবার জন্য প্রকাশিত নোটিশ এখানে দেখা যাবে।',
  'Download attachment': 'সংযুক্তি ডাউনলোড করুন',
  'Events & holidays': 'অনুষ্ঠান ও ছুটি',
  'No events this month': 'এই মাসে কোনো অনুষ্ঠান নেই',
  'Holiday': 'ছুটি',
  'Event': 'অনুষ্ঠান',
  'Previous month': 'আগের মাস',
  'Next month': 'পরের মাস',
  'Our teachers': 'আমাদের শিক্ষকবৃন্দ',
  'No teacher profiles yet': 'এখনো কোনো শিক্ষকের প্রোফাইল নেই',
  'Teacher profiles will appear here once they are added.': 'শিক্ষকের প্রোফাইল যোগ করা হলে এখানে দেখা যাবে।',
  'Merit list': 'মেধা তালিকা',
  'The merit list isn’t published yet': 'মেধা তালিকা এখনো প্রকাশিত হয়নি',
  'Top results appear here after the school publishes them.': 'প্রতিষ্ঠান প্রকাশ করার পর শীর্ষ ফলাফল এখানে দেখা যাবে।',
  'GPA': 'জিপিএ',
  'Class': 'শ্রেণি',
  'Section': 'শাখা',
  'Result lookup': 'ফলাফল অনুসন্ধান',
  'Roll or student ID': 'রোল বা শিক্ষার্থী আইডি',
  'Date of birth': 'জন্ম তারিখ',
  'Exam': 'পরীক্ষা',
  'Exam ID': 'পরীক্ষার আইডি',
  'Latest published exam': 'সর্বশেষ প্রকাশিত পরীক্ষা',
  'Find result': 'ফলাফল খুঁজুন',
  'Searching…': 'খোঁজা হচ্ছে…',
  'No result found for these details.': 'এই তথ্যে কোনো ফলাফল পাওয়া যায়নি।',
  'Online results aren’t available': 'অনলাইন ফলাফল পাওয়া যাচ্ছে না',
  'The school hasn’t turned on public result lookup.': 'প্রতিষ্ঠানটি এখনো অনলাইন ফলাফল চালু করেনি।',
  'Subject': 'বিষয়',
  'Marks': 'নম্বর',
  'Grade': 'গ্রেড',
  'Grade point': 'গ্রেড পয়েন্ট',
  'Total': 'মোট',
  'Print': 'প্রিন্ট',
  'Too many attempts. Please wait a minute and try again.': 'অনেকবার চেষ্টা করা হয়েছে। এক মিনিট পর আবার চেষ্টা করুন।',
  'Class routine': 'ক্লাস রুটিন',
  'No routine published': 'কোনো রুটিন প্রকাশিত হয়নি',
  'The class routine will appear here once it is set up.': 'রুটিন তৈরি হলে এখানে দেখা যাবে।',
  'Day': 'দিন',
  'Student ID': 'শিক্ষার্থী আইডি',
  'Roll number': 'রোল নম্বর',
  'More than one student matches. Enter the student ID instead.': 'একাধিক শিক্ষার্থী মিলে গেছে। রোলের বদলে শিক্ষার্থী আইডি দিন।',
  'Choose a form for this block (Website › Forms).': 'এই ব্লকের জন্য একটি ফর্ম বেছে নিন (ওয়েবসাইট › ফর্ম)।',
  'Please contact the school office.': 'প্রতিষ্ঠানের অফিসে যোগাযোগ করুন।',
  'Enter a number': 'একটি সংখ্যা দিন',
  'Choose one of the options': 'একটি অপশন বেছে নিন',
  'Online payment is in test mode.': 'অনলাইন পেমেন্ট পরীক্ষামূলক মোডে আছে।',
  'Time': 'সময়',
  'Teacher': 'শিক্ষক',
  'Students': 'শিক্ষার্থী',
  'Teachers': 'শিক্ষক',
  'Classes': 'শ্রেণি',
  'Years of excellence': 'বছরের পথচলা',
  'Figures will appear once the school’s records are set up.': 'প্রতিষ্ঠানের তথ্য যুক্ত হলে সংখ্যাগুলো দেখা যাবে।',
  'Admission enquiry': 'ভর্তি সংক্রান্ত জিজ্ঞাসা',
  'Student’s name': 'শিক্ষার্থীর নাম',
  'Guardian’s name': 'অভিভাবকের নাম',
  'Mobile number': 'মোবাইল নম্বর',
  'Class interested in': 'কোন শ্রেণিতে ভর্তি',
  'Message': 'বার্তা',
  'Send enquiry': 'জিজ্ঞাসা পাঠান',
  'Sending…': 'পাঠানো হচ্ছে…',
  'Thank you! We’ve received your enquiry and will contact you soon.': 'ধন্যবাদ! আপনার জিজ্ঞাসা পেয়েছি, শীঘ্রই যোগাযোগ করা হবে।',
  'Couldn’t send. Please check the form and try again.': 'পাঠানো যায়নি। ফর্মটি দেখে আবার চেষ্টা করুন।',
  'This field is required': 'এই ঘরটি পূরণ করা আবশ্যক',
  'Enter a valid email': 'সঠিক ইমেইল দিন',
  'Enter a valid mobile number': 'সঠিক মোবাইল নম্বর দিন',
  'We only use these details to reply to your enquiry.': 'আপনার জিজ্ঞাসার উত্তর দিতেই শুধু এই তথ্য ব্যবহার করা হবে।',
  'Pay fees online': 'অনলাইনে ফি পরিশোধ',
  'Online payment isn’t available yet': 'অনলাইন পেমেন্ট এখনো চালু হয়নি',
  'Please contact the school office to pay fees.': 'ফি পরিশোধে প্রতিষ্ঠানের অফিসে যোগাযোগ করুন।',
  'Go to the guardian portal': 'অভিভাবক পোর্টালে যান',
  'Courses': 'কোর্স',
  'Coming soon': 'শীঘ্রই আসছে',
  'Online courses will be available here soon.': 'অনলাইন কোর্স শীঘ্রই এখানে পাওয়া যাবে।',
  'Ask us anything': 'যেকোনো প্রশ্ন করুন',
  'Type your question…': 'আপনার প্রশ্ন লিখুন…',
  'Send': 'পাঠান',
  'Answers are AI-generated from the school’s information and may be incomplete. Please confirm with the office.': 'উত্তরগুলো প্রতিষ্ঠানের তথ্য থেকে এআই তৈরি করে, অসম্পূর্ণ হতে পারে। অফিসে নিশ্চিত হয়ে নিন।',
  'Demo mode': 'ডেমো মোড',
  'The assistant is in demo mode until an AI key is configured.': 'এআই কী সেট না করা পর্যন্ত সহকারী ডেমো মোডে আছে।',
  'Chat is live on the published site.': 'চ্যাট প্রকাশিত সাইটে চালু থাকবে।',
  'Open chat': 'চ্যাট খুলুন',
  'Close chat': 'চ্যাট বন্ধ করুন',
  'Live data appears once the site is connected.': 'সাইট সংযুক্ত হলে লাইভ তথ্য দেখা যাবে।',
  'Couldn’t load this section.': 'এই অংশটি লোড করা যায়নি।',
  'Add content in the editor': 'এডিটরে কনটেন্ট যোগ করুন',
  'Map location not set': 'ম্যাপের অবস্থান দেওয়া হয়নি',
  'Add a video link in the editor': 'এডিটরে ভিডিও লিংক দিন',
  'This embed was blocked because it isn’t from an allowed site.': 'অনুমোদিত সাইট থেকে না হওয়ায় এই এমবেডটি আটকানো হয়েছে।',
  'Question': 'প্রশ্ন',
  'View all': 'সব দেখুন',
  'Today': 'আজ',
  'Sun': 'রবি', 'Mon': 'সোম', 'Tue': 'মঙ্গল', 'Wed': 'বুধ', 'Thu': 'বৃহঃ', 'Fri': 'শুক্র', 'Sat': 'শনি',

  /* Shop, courses (LMS), cart, checkout, account (Website Builder v2) */
  'Days': 'দিন', 'Hours': 'ঘণ্টা', 'Minutes': 'মিনিট', 'Seconds': 'সেকেন্ড',
  'Add to cart': 'কার্টে যোগ করুন',
  'Added to cart': 'কার্টে যোগ হয়েছে',
  'Out of stock': 'স্টকে নেই',
  'In stock': 'স্টকে আছে',
  'View cart': 'কার্ট দেখুন',
  'Cart': 'কার্ট',
  'Your cart is empty': 'আপনার কার্ট খালি',
  'Add some products or courses to get started.': 'শুরু করতে কিছু পণ্য বা কোর্স যোগ করুন।',
  'Continue shopping': 'কেনাকাটা চালিয়ে যান',
  'Browse courses': 'কোর্স দেখুন',
  'Checkout': 'চেকআউট',
  'Remove': 'সরান',
  'Quantity': 'পরিমাণ',
  'Subtotal': 'উপমোট',
  'Shipping': 'শিপিং',
  'Free': 'বিনামূল্যে',
  'Order summary': 'অর্ডার সারাংশ',
  'Full name': 'পুরো নাম',
  'Delivery address': 'ডেলিভারি ঠিকানা',
  'Address line': 'ঠিকানা',
  'City': 'শহর',
  'Area': 'এলাকা',
  'Postcode': 'পোস্ট কোড',
  'Payment method': 'পেমেন্ট পদ্ধতি',
  'Cash on delivery': 'ক্যাশ অন ডেলিভারি',
  'Place order': 'অর্ডার করুন',
  'Placing order…': 'অর্ডার করা হচ্ছে…',
  'Order placed': 'অর্ডার সম্পন্ন হয়েছে',
  'Thank you — your order has been placed.': 'ধন্যবাদ — আপনার অর্ডার সম্পন্ন হয়েছে।',
  'Order number': 'অর্ডার নম্বর',
  'Order status': 'অর্ডার অবস্থা',
  'Pending': 'অপেক্ষমাণ',
  'Paid': 'পরিশোধিত',
  'Fulfilled': 'সম্পন্ন',
  'Cancelled': 'বাতিল',
  'Refunded': 'ফেরত দেওয়া হয়েছে',
  'Demo payment — no money moves': 'ডেমো পেমেন্ট — কোনো টাকা লেনদেন হয় না',
  'This is a simulated checkout for testing.': 'এটি পরীক্ষার জন্য একটি অনুকরণীয় চেকআউট।',
  'Simulate a successful payment': 'সফল পেমেন্ট অনুকরণ করুন',
  'Simulate a failed payment': 'ব্যর্থ পেমেন্ট অনুকরণ করুন',
  'Pay now': 'এখনই পরিশোধ করুন',
  'Download': 'ডাউনলোড',
  'Go to your course': 'আপনার কোর্সে যান',
  'Track your order': 'আপনার অর্ডার ট্র্যাক করুন',
  'Look up an order': 'অর্ডার খুঁজুন',
  'Order not found': 'অর্ডার পাওয়া যায়নি',
  'Check the order number and email address.': 'অর্ডার নম্বর ও ইমেইল ঠিকানা যাচাই করুন।',
  'Shop': 'দোকান',
  'All categories': 'সব বিভাগ',
  'Search products': 'পণ্য খুঁজুন',
  'Search courses': 'কোর্স খুঁজুন',
  'No products yet': 'এখনো কোনো পণ্য নেই',
  'Products will appear here once they’re published.': 'প্রকাশিত হলে পণ্য এখানে দেখা যাবে।',
  'No courses yet': 'এখনো কোনো কোর্স নেই',
  'Courses will appear here once they’re published.': 'প্রকাশিত হলে কোর্স এখানে দেখা যাবে।',
  'Enrol': 'ভর্তি হোন',
  'Enrolling…': 'ভর্তি করা হচ্ছে…',
  'Buy now': 'এখনই কিনুন',
  'View course': 'কোর্স দেখুন',
  'Instructor': 'প্রশিক্ষক',
  'Curriculum': 'পাঠ্যক্রম',
  'lessons': 'পাঠ',
  'Level': 'স্তর',
  'Duration': 'সময়কাল',
  'Sign in': 'সাইন ইন',
  'Sign up': 'নিবন্ধন করুন',
  'Log out': 'লগ আউট',
  'Account': 'অ্যাকাউন্ট',
  'My orders': 'আমার অর্ডার',
  'My courses': 'আমার কোর্স',
  'Password': 'পাসওয়ার্ড',
  'Create account': 'অ্যাকাউন্ট তৈরি করুন',
  'Already have an account? Sign in': 'ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন',
  'New here? Create an account': 'নতুন? অ্যাকাউন্ট তৈরি করুন',
  'Invalid email or password': 'ইমেইল বা পাসওয়ার্ড সঠিক নয়',
  'You need an account to enrol in this course.': 'এই কোর্সে ভর্তি হতে অ্যাকাউন্ট প্রয়োজন।',
  'Continue': 'চালিয়ে যান',
  'Mark complete': 'সম্পন্ন হিসেবে চিহ্নিত করুন',
  'Completed': 'সম্পন্ন হয়েছে',
  'Next lesson': 'পরবর্তী পাঠ',
  'Previous lesson': 'আগের পাঠ',
  'Your progress': 'আপনার অগ্রগতি',
  'This lesson is a free preview.': 'এই পাঠটি একটি বিনামূল্যের প্রিভিউ।',
  'Enrol to unlock the full course.': 'পুরো কোর্স আনলক করতে ভর্তি হোন।',
  'You already own this course.': 'আপনি ইতিমধ্যে এই কোর্সটির মালিক।',
  'No lessons yet': 'এখনো কোনো পাঠ নেই',
  'Please sign in to view your account.': 'আপনার অ্যাকাউন্ট দেখতে সাইন ইন করুন।',
  'You haven’t placed any orders yet.': 'আপনি এখনো কোনো অর্ডার করেননি।',
  'You’re not enrolled in any course yet.': 'আপনি এখনো কোনো কোর্সে ভর্তি হননি।',
};

export function siteString(lang: SiteLang, key: string, vars?: Record<string, string | number>): string {
  let s = lang === 'bn' ? BN[key] ?? key : key;
  if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
  return s;
}

export const SITE_LOCALE: Record<SiteLang, string> = { en: 'en-GB', bn: 'bn-BD' };

export function formatSiteDate(value: string | Date | undefined, lang: SiteLang, opts: Intl.DateTimeFormatOptions = { day: 'numeric', month: 'short', year: 'numeric' }): string {
  if (!value) return '';
  const d = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(d.getTime())) return '';
  try {
    return new Intl.DateTimeFormat(SITE_LOCALE[lang], { timeZone: 'Asia/Dhaka', ...opts }).format(d);
  } catch {
    return d.toDateString();
  }
}

export function formatSiteNumber(n: number, lang: SiteLang): string {
  try {
    return new Intl.NumberFormat(SITE_LOCALE[lang]).format(n);
  } catch {
    return String(n);
  }
}

const CURRENCY_SYMBOL: Record<string, string> = { BDT: '৳', USD: '$', EUR: '€', GBP: '£', INR: '₹' };

/** `৳1,234` — a currency symbol plus a locale-formatted amount (2 decimals only when not a whole number). */
export function formatSiteMoney(amount: number, currency: string, lang: SiteLang): string {
  const symbol = CURRENCY_SYMBOL[currency] ?? `${currency} `;
  const whole = Number.isInteger(amount);
  try {
    return `${symbol}${new Intl.NumberFormat(SITE_LOCALE[lang], { minimumFractionDigits: whole ? 0 : 2, maximumFractionDigits: 2 }).format(amount)}`;
  } catch {
    return `${symbol}${amount.toFixed(whole ? 0 : 2)}`;
  }
}
